initial commit
:wq

]      master -> master
branch 'master' set up to track 'origin/master'.
PS C:\Users\pc\mkdir mern-portfolio\mern-portfolio-frontend> git branch
-m master main
PS C:\Users\pc\mkdir mern-portfolio\mern-portfolio-frontend> git push -u
origin main
To https://github.com/kandagatla-raju/MyPortfolio.git
 ! [rejected]        main -> main (fetch first)
 error: failed to push some refs to
 'https://github.com/kandagatla-raju/MyPortfolio.git'
 hint: Updates were rejected because the remote contains work that you
 do not
 hint: have locally. This is usually caused by another repository
 pushing to
 hint: the same ref. If you want to integrate the remote changes, use
 hint: 'git pull' before pushing again.
 hint: See the 'Note about fast-forwards' in 'git push --help' for
 details.
 PS C:\Users\pc\mkdir mern-portfolio\mern-portfolio-frontend> git pull
 origin main --rebase
 remote: Enumerating objects: 3, done.
 remote: Counting objects: 100% (3/3), done.
 remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
 Unpacking objects: 100% (3/3), 870 bytes | 33.00 KiB/s, done.
 From https://github.com/kandagatla-raju/MyPortfolio
  * branch            main       -> FETCH_HEAD

  :wq

  .git/COMMIT_EDITMSG[+] [unix] (13:22 19/05/2025)
  46,1 Bot-- INSERT --recording @a